name: QEMU AST2600 Setup CI

on: [push, workflow_dispatch]

jobs:
  openbmc-test-automation:
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 60
    permissions:
      contents: read

    env:
      OPENBMC_IMAGE_URL: https://github.com/Alone0506/openbmc/releases/download/CI_Test/obmc-phosphor-image-evb-ast2600.static.mtd
      HOST: 127.0.0.1
      USER: root
      PASS: 0penBmc
      SSH_PORT: 2222
      HTTPS_PORT: 2443
      IPMI_PORT: 2623
      QEMU_LOG: ${{ github.workspace }}/qemu.log

    defaults:
      run:
        shell: bash

    outputs:
      logs_id: ${{ steps.logs.outputs.artifact-id }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Download OpenBMC image
        run: curl -L -o image.mtd $OPENBMC_IMAGE_URL

      - name: Install host dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            qemu-system-arm \
            openssh-client \
            sshpass \
            ipmitool \
            python3-venv \
            python3-pip

      - name: Launch AST2600 EVB in QEMU
        run: >
          nohup qemu-system-arm
          -m 1G
          -M ast2600-evb
          -nographic
          -drive file=image.mtd,format=raw,if=mtd
          -net nic
          -net user,hostfwd=tcp:127.0.0.1:${SSH_PORT}-:22,hostfwd=tcp:127.0.0.1:${HTTPS_PORT}-:443,hostfwd=udp:127.0.0.1:${IPMI_PORT}-:623,hostname=qemu
          >"$QEMU_LOG" 2>&1 &

      - uses: actions/checkout@v6
        with:
          repository: Alone0506/openbmc-test-automation
          path: tests

      - name: Install openbmc-test-automation deps
        run: |
          python3 -m venv tests/.venv
          tests/.venv/bin/pip install -U pip -r tests/requirements.txt

      - name: Wait QEMU SSH work
        run: |
          for i in {1..30}; do
            sshpass -p "$PASS" ssh \
              -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              -o LogLevel=ERROR \
              -p $SSH_PORT $USER@$HOST true && exit 0
            echo "SSH not ready yet (attempt ${i}/30)"
            sleep 10
          done
          tail -200 "$QEMU_LOG"
          exit 1

      - name: Run Robot
        working-directory: tests
        run: |
          . .venv/bin/activate
          robot -V env.py templates/test_openbmc_setup.robot

      - name: Cleanup
        if: always()
        run: pkill -f qemu-system-arm || true

      - name: Prepare artifact files
        if: always()
        run: |
          mkdir -p artifact
          cp "$QEMU_LOG" artifact/ || true
          cp tests/*.html artifact/ || true
          cp tests/*.xml artifact/ || true

      - uses: actions/upload-artifact@v7
        if: always()
        id: logs # add artifact tag
        with:
          path: artifact/*

  deploy-pages:
    needs: openbmc-test-automation
    if: always()
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - name: Download logs
        env:
          LOGID: ${{needs.openbmc-test-automation.outputs.logs_id}}
        uses: actions/download-artifact@v7
        with:
          artifact-ids: ${{ env.LOGID }}
          path: tests # download to tests folder

      - name: Prepare Pages Content
        if: always()
        run: |
          RUN_ID=$(date +%Y%m%d-%H%M%S)

          mkdir -p site/runs/$RUN_ID

          cp tests/*.html site/runs/$RUN_ID/ || true
          cp tests/*.xml site/runs/$RUN_ID/ || true
          cp "$QEMU_LOG" site/runs/$RUN_ID/ || true

          echo "<html><body><h1>Files</h1><ul>" > site/index.html

          for f in site/runs/$RUN_ID/*; do
            name=$(basename "$f")
            echo "<li><a href=\"runs/$RUN_ID/$name\" target=\"_blank\">$name</a></li>" >> site/index.html
          done

          echo "</ul></body></html>" >> site/index.html

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
